### ISSUE TITLE
travisのbuildが失敗する件

### ISSUE THREAD

**Issue by syui** [ArchLinuxJP/docker-arch#3]
## new

この問題に対応するためリポジトリを分離しました。

https://github.com/ArchLinuxJP/docker-yaourt

## old

現在2つの理由で失敗しているように見えます。travisの主要なlogはこちらです。

```bash
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

この問題ついてはyaourtのイメージを作成する時に失敗しているようで、travis上で実行する以下のコマンドが原因だと見られます。

> .travis.yml

```yml
docker run -v /var/run/docker.sock:/var/run/docker.sock --privileged -it yaourt /bin/bash /mkimage-arch-jp.sh;
docker push $DOCKER_TEARM/archlinux-yaourt;
```

よって、この問題については一旦、yaourtのイメージを作成する処理をやめることで一時的な対処とします。

次に以下のエラーが出る問題があります。

```bash
docker: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory
The command "docker run -v /var/run/docker.sock:/var/run/docker.sock --privileged -it tmp /bin/bash /mkimage-arch-jp.sh" exited with 127.
```

これは`pacman -Scc`のような処理が原因かもしれない考えていますが、はっきりとしたことは調査していません。

```bash
Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove ALL files from cache? [y/N] 
Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] 
removing unused sync repositories...
docker: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory
```

**Comment by syui** [comment]
> When a long running command or compile step regularly takes longer than 10 minutes without producing any output, you can adjust your build configuration to take that into consideration.

https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

上のようにあることから、travisは10分以上かかっているbuild処理を制限するように変更したようです。

リポジトリを統合したことによってtravisに集中的に負担がかかってしまい、build時間が増えてしまったことが原因ですが、この前は、archlinux-yaourtのイメージを作成する処理を消して対応しました。

#867792e

これに対する対処法で最も順当なのはリポジトリを分離することですが、現時点でどうすべきかはまだ考えていません。一応、これまでの情報を再度まとめておくことにします。

### archlinux-yaourtの利点

archlinux-yaourtの一つの利点は`dockerfile`に`yaourt -S $app`のような処理を直接書くことができるところにあります。

### なぜイメージを日々アップデートしなければならないか

archlinux-yaourtをtravis-ciのcronを介して日々アップデートする理由は、他のdocker imageと同様、アップデートされずに古くなってしまったarchlinuxのイメージが`pacman -Syu`ができなくなることによって壊れてしまう危険を回避するためです。また、当該docker imageを使用する利用者にとっても古いイメージはアップデートの時間がかかってしまいその辺のタイムロスを縮小する狙いもあります。(dockerfileに最初にpacman -Syuのようなパッケージアップデートの処理を書く人が多いため)

**Comment by syui** [comment]
#867792ee423b1de557bbc1508db54037e99da58c

**Comment by syui** [comment]
この問題に対応するため、yaourtのイメージを生成するリポジトリを分離しました。
https://github.com/ArchLinuxJP/docker-yaourt

**Comment by syui** [comment]
再度、リポジトリを作成してCIを回して初めて気づきましたが、問題はビルド時間ではなく出力がない時間であるため、本家であるdocker-archの方で、travis.ymlを書いて実験してみます。

**Comment by syui** [comment]
> .travis.yml

```yml
after_success:
        - travis_wait 30 mvn install
        - docker run -v /var/run/docker.sock:/var/run/docker.sock --privileged -it yaourt /bin/bash /mkimage-arch-jp.sh
\"}"
```

こんな感じで書いたら通りましたが、正直なところよく分かりません。そもそも出力がないというけれど、普通にありましたし、そのあたりよくわからない感じです。

**Comment by k3nsuk3** [comment]
@syui さん
`travis_wait 30 mvn install` ですが，これは `mvn install` の実行中は毎分ごとに 30 分経過まで short line を出力するという内容になります．

なので，以下の様に修正すべきかと思います．

```yaml
after_success:
    - travis_wait 30 docker run -v /var/run/docker.sock:/var/run/docker.sock --privileged -it yaourt /bin/bash /mkimage-arch-jp.sh
```

本 Issue に関してですが， yaourt イメージ作成時のパッケージダウンロード時にミラーサーバからの通信が stuck してしまい，出力が無いまま 10 分経過して…ってのがありそうかなーと思いました．

**Comment by syui** [comment]
なるほど、ありがとうございます。

**Comment by syui** [comment]
例えば、`if`を使う場合などは`if`の前に`travis_wait`を置いたほうがいいのでしょうか。

```yml
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
    travis_wait 30 docker run ...;
  fi
```

```yml
after_success:
- travis_wait 30 if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker run ...;
  fi
```

**Comment by syui** [comment]
ちょっと実験中です。

yaourtのdocker pushだけが何故か成功していない感じがする。

**Comment by syui** [comment]
理由は分かりませんが、travis-ciを回して何故か以下のような結果になりました。

### build成功、しかし、yaourtにdocker push失敗

```yml
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
        travis_wait 30 docker run -v /var/run/docker.sock:/var/run/docker.sock --privileged -it yaourt /bin/bash /mkimage-arch-jp.sh;
        ...
  fi
```

```yml
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
        travis_wait 30 docker run -v /var/run/docker.sock:/var/run/docker.sock --privileged -it yaourt /bin/bash /mkimage-arch-jp.sh;
        travis_wait 30 docker push $DOCKER_TEARM/archlinux-yaourt;
        ...
  fi
```

```yml
after_success:
- travis_wait 30 if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker run -v /var/run/docker.sock:/var/run/docker.sock --privileged -it yaourt /bin/bash /mkimage-arch-jp.sh;
        ...
  fi
```

### build成功、yaourtにdocker push成功

```yml
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
        travis_wait 30 mvn install;
        docker run -v /var/run/docker.sock:/var/run/docker.sock --privileged -it yaourt /bin/bash /mkimage-arch-jp.sh;
        ...
  fi
```

**Comment by k3nsuk3** [comment]
@syui さん

b5c5342 と 132b1a3 については， `mkimage-arch-jp.sh` の中身の実行には成功している（`Success` が出力されている）ようですが，その後以下のようなログが出力され， `exit with 1` となっているようです．

```
Still running (1 of 30): docker run -v /var/run/docker.sock:/var/run/docker.sock --privileged -it yaourt /bin/bash /mkimage-arch-jp.sh
The command docker run -v /var/run/docker.sock:/var/run/docker.sock --privileged -it yaourt /bin/bash /mkimage-arch-jp.sh exited with 1.

Log:

the input device is not a TTY
/home/travis/.travis/job_stages: line 169: 10059 Terminated              travis_jigger $! $timeout $cmd
```

ab6300e は `job_stages` にコマンドを渡す部分で `syntax error near unexpected token 'then'` となっていることから，おそらく `travis_wait` に if 文をそのまま渡すことは出来ないのかなと思います．

b5c5342 と 132b1a3 で出力されたログについて調べてみますが，パッケージダウンロードで stuck するのが原因であると仮定するなら，[travis_retry](https://docs.travis-ci.com/user/common-build-problems/#Timeouts-installing-dependencies) の利用を検討されてもいいかもしれません．

-----
## 解決案
`mkimage-arch-jp.sh` を用いた yaourt イメージの作成時に， `travis_wait` ではなく `travis_retry` を用いる．

```yaml
travis_retry docker run -v /var/run/docker.sock:/var/run/docker.sock --privileged -it yaourt /bin/bash /mkimage-arch-jp.sh;
```

**Comment by k3nsuk3** [comment]
@syui さん

エラーログに関してですが，まさしくこれかなと思います．
travis-ci/travis-ci#6934

`travis_wait` を `docker` コマンドのために使うことは出来ないそうなので，本件の用途では `travis_wait` は使えないかなと思います．

**Comment by syui** [comment]
調べてくださって本当に助かります。

今、pushしてtravisを回してみました。もしよろしければ、 @k3nsuk3 さんがmasterにpushしてもらっても構いませんよ。

ようはちゃんと動いていることが重要ですから。

**Comment by syui** [comment]
いけたみたいです。

**Comment by k3nsuk3** [comment]
@syui さん
とりあえず，様子見ですね😅
何も無いことを祈りますが，もし何かあったら僕の方でも Commit, Push 対応します！

**Comment by syui** [comment]
助かります!
